In [1]:
#import numpy
import numpy as np
#function called randomization with input arg n
def randamization(n):
    #use of random.randint to generate an array of size n*1
    A = np.random.randint(10,size=(n,1))
    #return the numpy array A
    return A

#main driver method
if __name__=='__main__':
    #get user input n
    n=int(input("Enter a positive integer n: "))
    #if input is negative, display invalid input
    if(n<=0):
        print("Invalid input!!")
    #else call the function randomization with input as n
    else:   
        print(randamization(n))
        

Enter a positive integer n: 15
[[2]
 [4]
 [1]
 [9]
 [9]
 [4]
 [5]
 [3]
 [5]
 [7]
 [4]
 [3]
 [1]
 [4]
 [0]]


In [2]:
import numpy as np
def operations(h,w):
   #Create random matrix from numbers 0-9 of size h x w.
   A = np.random.randint(10,size=(h,w))
   B = np.random.randint(10,size=(h,w))
   #calculate sum
   s = A+B
   return A,B,s #return values
A,B,s = operations(2,2)
print("A:\n",A)
print("B:\n",B)
print("s:\n",s)
#CODE ENDS HERE-----------------

A:
 [[2 0]
 [7 2]]
B:
 [[2 5]
 [5 4]]
s:
 [[ 4  5]
 [12  6]]


In [30]:
import numpy as np
import math
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    result=(inputs*np.transpose(weights))
    result=result[0][0]+result[1][1]
    
    out=math.tanh(result)
    out=np.array([[out]])
    return out
    #Your code here
Input=np.array([[2],[1]])
Weights=np.array([[3],[1]])
output=neural_network(Input,Weights)
print(output)


[[0.99999834]]


In [27]:
inpu=np.array([[2],[1]])
inpu

array([[2],
       [1]])

In [25]:
inpu.shape

(1, 2)

In [13]:
import math

In [33]:
import numpy as np
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if (x<=y):
        return x*y
    else:
        return x/y
        
    #Your code here
x=int(input())
y=int(input())
print(scalar_function(x,y))

5
2
2.5


In [35]:
def vector_function(x, y):
    f=np.vectorize(scalar_function)
    return f(x,y)

In [36]:
# Debugged Code To find metices sum
def get_sum_metrics(predictions, metrics=None):
    #Check if metrics is None, if so then make it empty list
    if metrics is None:
        metrics = []
        
    for i in range(3):
        metrics.append(lambda x, i=i: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics

# Main Driver Function
if __name__ == "__main__":
    print(get_sum_metrics(0))
    print(get_sum_metrics(1))

3
6
